export declare function getName(profile: any): any;
export declare function getGivenName(profile: any): any;
export declare function getFamilyName(profile: any): any;
export declare function getDescription(profile: any): any;
export declare function getAvatarUrl(profile: any): string;
export declare function getVerifiedAccounts(profile: any, verifications?: any[]): any[];
export declare function getOrganizations(profile: any): any;
export declare function getConnections(profile: any): any[];
export declare function getAddress(profile: any): any;
export declare function getBirthDate(profile: any): any;
